name: Deploy SAM Application from Branch

on:
  push:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Add your build/deploy steps here
      - name: Example step
        run: echo "Deploying application..."

      # Notify Slack
      - name: Notify Slack
        uses: act10ns/slack@v2
        if: always()
        with:
          webhook-url: ${{ secrets.SLACK_WEBHOOK_URL }}
          status: ${{ job.status }}
          config: .github/slack-configs/my_slack_message.yml
