name: Deploy SAM Application from Branch

on:
  push:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set environment variables
        run: |
          echo "BUILD_START=$(date +%s)" >> $GITHUB_ENV
          echo "SHORT_SHA=${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Simulate deployment
        run: echo "Deploying application..."

      - name: Calculate build duration
        run: |
          echo "DURATION=$(( $(date +%s) - $BUILD_START ))" >> $GITHUB_ENV

      - name: Generate Slack payload
        run: |
          STATUS="${{ job.status == 'success' && '✅ Succeeded' || job.status == 'failure' && '❌ Failed' || '⚠️ Cancelled' }}"
          COLOR="${{ job.status == 'success' && '#2eb886' || job.status == 'failure' && '#e01e5a' || '#daa038' }}"
          COMMIT_URL="${{ github.event.head_commit.url }}"
          RUN_LOG_URL="${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          AUTHOR="${{ github.event.head_commit.author.name }}"
          MESSAGE="${{ github.event.head_commit.message }}"

          export STATUS COLOR GITHUB_REPOSITORY SHORT_SHA COMMIT_URL AUTHOR GITHUB_JOB="${{ github.job }}" \
                 GITHUB_WORKFLOW="${{ github.workflow }}" GITHUB_EVENT_NAME="${{ github.event_name }}" \
                 RUN_LOG_URL DURATION="${{ env.DURATION }}" COMMIT_MESSAGE="$MESSAGE"

          envsubst < .github/slack-configs/mail.template.json > slack_payload.json

      - name: Send Slack notification
        uses: slackapi/slack-github-action@v1.26.0
        with:
          payload-file-path: slack_payload.json
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
