name: Deploy SAM Application from Branch

on:
  push:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up meta‐vars
        run: |
          echo "BUILD_START=$(date +%s)" >> $GITHUB_ENV
          echo "SHORT_SHA=${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Deploy application
        run: echo "🚀 Deploying application.....…"

      - name: Calculate build duration
        run: |
          END=$(date +%s)
          echo "DURATION=$((END - BUILD_START))" >> $GITHUB_ENV

      - name: Generate Slack payload
        run: |
          export STATUS="${{ job.status == 'success' && '✅ Succeeded' || job.status == 'failure' && '❌ Failed' || '⚠️ Cancelled' }}"
          export COLOR="${{ job.status == 'success' && '#2eb886' || job.status == 'failure' && '#e01e5a' || '#daa038' }}"
          export GITHUB_REPOSITORY="${{ github.repository }}"
          export COMMIT_URL="${{ github.event.head_commit.url }}"
          export AUTHOR="${{ github.event.head_commit.author.name }}"
          export GITHUB_JOB="${{ github.job }}"
          export GITHUB_WORKFLOW="${{ github.workflow }}"
          export GITHUB_EVENT_NAME="${{ github.event_name }}"
          export RUN_LOG_URL="${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          export COMMIT_MESSAGE="${{ github.event.head_commit.message }}"
          # Populate template:
          envsubst < .github/slack-configs/mail.template.json > slack_payload.json

      - name: Send Slack notification
        uses: slackapi/slack-github-action@v1.26.0
        with:
          payload-file-path: slack_payload.json
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
