name: Deploy SAM Application from Branch

on:
  #push:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set short SHA
        run: echo "SHORT_SHA=${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Deploy step
        run: echo "Deploying application..."

      - name: Send custom JSON data to Slack workflow
        id: slack
        uses: slackapi/slack-github-action@v1.26.0
        with:
          payload: |
            {
              "attachments": [
                {
                  "color": "${{ job.status == 'success' && '#2eb886' || job.status == 'failure' && '#e01e5a' || '#daa038' }}",
                  "blocks": [
                    {
                      "type": "section",
                      "text": {
                        "type": "mrkdwn",
                        "text": "*${{ job.status == 'success' && ':white_check_mark: Succeeded' || job.status == 'failure' && ':x: Failed' || ':warning: Cancelled' }} GitHub Actions*"
                      }
                    },
                    {
                      "type": "section",
                      "fields": [
                        {
                          "type": "mrkdwn",
                          "text": "*Repo*\n<https://github.com/${{ github.repository }}|${{ github.repository }}>"
                        },
                        {
                          "type": "mrkdwn",
                          "text": "*Commit*\n<${{ github.event.head_commit.url }}|${{ env.SHORT_SHA }}>"
                        },
                        {
                          "type": "mrkdwn",
                          "text": "*Author*\n${{ github.event.head_commit.author.name }}"
                        },
                        {
                          "type": "mrkdwn",
                          "text": "*Job*\n`${{ github.job }}`"
                        },
                        {
                          "type": "mrkdwn",
                          "text": "*Workflow*\n`${{ github.workflow }}`"
                        },
                        {
                          "type": "mrkdwn",
                          "text": "*Event*\n`${{ github.event_name }}`"
                        },
                        {
                          "type": "mrkdwn",
                          "text": "*Build Logs*\n<${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|View Logs>"
                        },
                        {
                          "type": "mrkdwn",
                          "text": "*Took*\n`${{ steps.calculate_duration.outputs.duration || 'N/A' }} sec`"
                        },
                        {
                          "type": "mrkdwn",
                          "text": "*Message*\n${{ github.event.head_commit.message }}"
                        }
                      ]
                    }
                  ]
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
